# Generated by Django 4.2.1 on 2024-09-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizattempt',
            old_name='attempt_date',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
