# Generated by Django 4.2.1 on 2024-09-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_attempt_date_quizattempt_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
